### ISSUE TITLE
Captions of PlantUML diagrams don't respect markdown formatting

### ISSUE THREAD

**Issue by fuhrmanator** [fuhrmanator/log210-notes-de-cours#1]
See https://github.com/jgm/pandocfilters/issues/81

**Comment by fuhrmanator** [comment]
Alternatives might be to make filter simply generate a file that is not embedded, but just linked with `![caption](generated_file.svg)`

**Comment by fuhrmanator** [comment]
I'm working around this by using a `hide-image=true` and `plantuml-filename=` options for the PlantUML filter.

**Comment by fuhrmanator** [comment]
Fixed (at least for LaTeX) with https://github.com/fuhrmanator/log210-notes-de-cours/commit/221b9374df8bdf2daa5736a764c93d50954f45a6#diff-bbb1f26b8a6a11294322c68624e4f5459c77f2366ea38b8485dda6524adf7243

**Comment by fuhrmanator** [comment]
Thanks to @dilawar for help at https://github.com/dilawar/dilawar/commit/ada7ee93a839e3fabf14e981ac8ce307984e781a#diff-de78ea8273d8480556c6ca3761357ae0bb8a0e4bfdfcc2c4937b31271001e2a6

**Comment by dilawar** [comment]
I am glad I could help.
