### ISSUE TITLE
Normaliser l'environnement pour construire le PDF

### ISSUE THREAD

**Issue by yvanross** [fuhrmanator/log210-notes-de-cours#6]
make pdf
mkdir -p build/pdf
mkdir -p build/images
pandoc --toc --toc-depth=2 --webtex --css=style.css --metadata-file=metadata.yml --filter filters/plantuml/plantuml.py --filter pandoc-citeproc --listing -V geometry:margin=1in --pdf-engine=pdflatex --template=templates/default.latex -o build/pdf/LOG210-notes-de-cours.pdf chapters/*.md
INFO: Not showing image plantuml-images/8aa0d414645fd7a7e6461179b1ab31b81de86bcc.pdf
INFO: Not showing image plantuml-images/0dd882459df622a44b0a37074b110023480929f9.pdf
INFO: Not showing image plantuml-images/f840e5d202181fb91006af23bdfb5696a6efe60c.pdf
INFO: Not showing image plantuml-images/32c55f94b599d9555f8e128c73f841d6053e56e1.pdf
INFO: Not showing image plantuml-images/f2a5459252d2f5e5877d7f3b5d871249e5c28144.pdf
INFO: Not showing image plantuml-images/25aa7c7c645afc82c1deca34a6f7f0bc0876a58c.pdf
INFO: Not showing image plantuml-images/59c49aa7edd61836707ae53597ebabc54bc0b0b1.pdf
INFO: Not showing image plantuml-images/ad88902e363a28d98ef4c485a0055a0d324ca8bf.pdf
INFO: Not showing image plantuml-images/db55c14dcce921a1f4506f017985dd36c4220b1d.pdf
INFO: Not showing image plantuml-images/e2dde28b09f4aec02ab274046f5839472afcb491.pdf
INFO: Not showing image plantuml-images/a21cc9b339807eff5b31bf6711063aee3922ba63.pdf
INFO: Not showing image plantuml-images/4f3054a55e2c6343181be67924fe56ed6b78b745.pdf
INFO: Not showing image plantuml-images/936aff773c6f5d36cb513bdac1a2a44420753136.pdf
INFO: Not showing image plantuml-images/01bf55a5e13e38ab44c77f3ed891f2ca8dfe08fb.pdf
INFO: Not showing image plantuml-images/f71dbf216f0a1ab50d187dd300de6b3ca601ce08.pdf
INFO: Not showing image plantuml-images/5741ce1b05b22b5f14eb7798d900c01fa43f1cfa.pdf
INFO: Not showing image plantuml-images/46330d9f6f4ad472ebad073d36a9c6180ef76fc4.pdf
INFO: Not showing image plantuml-images/9fc8735360ddbd7f743feda8177fab872983a463.pdf
INFO: Not showing image plantuml-images/5cf6d4191ac7e2cb4da775da4dd1cdece7ddd82a.pdf
INFO: Not showing image plantuml-images/77782fd1ec824f941096b1201b242576aa5e4294.pdf
INFO: Not showing image plantuml-images/dbfd4e0b023e178d52354cd4e5208eb7850e93a3.pdf
Error producing PDF.
! LaTeX Error: File `libertinus.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 
         
l.18 \usepackage

make: *** [build/pdf/LOG210-notes-de-cours.pdf] Error 43
rossypro:log210-notes-de-cours rossypro$

**Comment by yvanross** [comment]
j'ai téléchargé le fichier sty du web et ca ne semble pas encore fonctionné.  J'ai commenté les paramètre de font et je semble plus près de la solution.  J'ai un problème avec 
! Undefined control sequence.
l.236 livre~\faBook

il ne reconnais pas \faBook comment est-ce que cette commande est traité....

**Comment by yvanross** [comment]
Autre erreur
Error running filter filters/plantuml/plantuml.py:
Error in $: not enough input

**Comment by fuhrmanator** [comment]
\faBook est le package fontawesome. 

Sur windows j’utilise MikTeX qui installe dynamiquement les packages LaTeX. J’imagine que sur Mac c’est TeXLive et tu dois avoir tous les packages. J’ignore comment les installer mais le fichier `metadata.yml` contient des `\usepackage` pour te donner une idée:

```
- \usepackage[style=french]{csquotes}
- \usepackage{fontawesome5}
- \usepackage{fontawesome}
- \usepackage{tcolorbox}
- \newtcolorbox{myquote}{colback=red!5!white, colframe=red!75!black}
- \renewenvironment{quote}{\begin{myquote}}{\end{myquote}}
- \usepackage{longtable,booktabs}
# https://tex.stackexchange.com/a/142319/17868
- \usepackage{courier}
```

**Comment by fuhrmanator** [comment]
Libertinus est aussi un package (font) LaTeX à  installer. P-e avec une installation complète  de texlive (plusieurs Go) tu auras tout?

**Comment by fuhrmanator** [comment]
Le readme mentionne:

    sudo apt-get install texlive-xetex ttf-dejavu

**Comment by yvanross** [comment]
L’équivalent mac de texlive est Mactex  que je suis en train d’installer.  Je te tiens au courant si ça fonctionne.

Yvan Ross, ing., M. Ing.
yvan.ross@gmail.com
https://www.linkedin.com/in/yvanross/
Gestion de projets RossY inc.
514-797-8894

**Comment by yvanross** [comment]
rossypro:log210-notes-de-cours rossypro$ make pdf
mkdir -p build/pdf
mkdir -p build/images
pandoc --toc --toc-depth=2 --webtex --css=style.css --metadata-file=metadata.yml --filter filters/plantuml/plantuml.py --filter pandoc-citeproc --listing -V geometry:margin=1in --pdf-engine=pdflatex --template=templates/default.latex -o build/pdf/LOG210-notes-de-cours.pdf chapters/*.md
Error running filter filters/plantuml/plantuml.py:
Error in $: not enough input
make: *** [build/pdf/LOG210-notes-de-cours.pdf] Error 83

**Comment by fuhrmanator** [comment]
Hmmm... avant à https://github.com/fuhrmanator/log210-notes-de-cours/issues/6#issue-674562958 ça créait des images dans ton log (ce qui veut dire que le filter Plantuml.py fonctionnait. As-tu revérifier Python? Après l'installation de LaTeX?

**Comment by fuhrmanator** [comment]
Pour simplifier les choses sur plusieurs plateformes, peut-être vaut-il la peine de considérer une image Docker personnalisée pour pandoc + python + latex? https://github.com/pandoc/dockerfiles#building-custom-images 

Ainsi on pourrait standardiser l'environnement de build (et aussi utiliser les Actions GitHub pour générer automatiquement le PDF). @yvanross as-tu déjà fait des docker personnalisés?

**Comment by fuhrmanator** [comment]
@yvanross dans la branche https://github.com/fuhrmanator/log210-notes-de-cours/tree/DockerBuild j'ai enfin quelque chose qui fonctionne plus ou moins avec Docker (les polices dans les images PlantUML ne sont pas bonnes, mais cela a été long juste d'avoir une config Docker pour l'environnement LaTeX personnalisé). Disons que j'ai appris plein de choses sur la config de Docker 🥰 

Veux-tu essayer cette branche? Pour construire l'image docker sur ta machine (je suppose que tu as docker sur ton Mac), il y a une commande dans le Makefile:

```bash
make install
``` 

Ça peut prendre longtemps car j'ai dû installer plein de packages TexLive en latex sur ubuntu. L'image fait plus de 3 G ⚠️ - je dois voir ce qu'on peut faire pour diminuer sa taille. Je n'ai pas réussi à bien configurer `tlmgr` (les packages s'installent dans l'image, mais `pdflatex` ne les trouve pas - p-e un problème de PATH dans l'image). Il y a plein de hacks (comme j'ai dû lancer pandoc avec sudo à cause de certains polices qui se construisent dynamiquement). 

En tout cas, ce résultat prouve que c'est théoriquement possible d'y arriver avec Docker et éventuellement des GitHub actions pour construire les notes. 

Après que l'image Docker est faite (c'est juste une fois), tu fais pour construire le PDF: 

```bash
make pdf
```

Je voudrais bien savoir si ça fonctionne sur ton mac :)

**Comment by fuhrmanator** [comment]
Voici les différences avec le PDF actuel et la version que je construisais sur Windows 10 avec mon environnement personnalisé:

- Plusieurs polices p.ex. "handwritten" en PlantUML ne sont pas installées dans l'image Docker et lorsque le filtre Pandoc génère le PDF, les polices ne sont pas là.
- J'ai dû "hacker" le format "pdf" dans le filtre PlantUML de Pandoc (une info sur le type souhaité (latex) est possiblement absent dans l'environnement Docker) - sinon, il générait les .png toujours (pas net dans le PDF, le texte des diagrammes n'est pas "recherchable").

**Comment by fuhrmanator** [comment]
@yvanross j'ai corrigé quelques problèmes, séparé le Docker du reste des choses, le ReadMe est à jour aussi.

**Comment by fuhrmanator** [comment]
S'il y a des problèmes avec la construction du PDF, on peut rouvrir ce billet.
